# cd C:\Users\aless\Documents\CluBee
# docker-compose up -d

services:
  db:
    image: clubee/clubee.database:latest
    container_name: postgres-container
    restart: always
    mem_limit: 1000m 
    ports:
      - "5432:5432"
    networks:
      - rede-clubee
    

  api:
    image: clubee/clubee.backend:latest
    container_name: springboot-container
    restart: always
    mem_limit: 2000m
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - rede-clubee


networks:
  rede-clubee:
    driver: bridge